version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        container_name: laravel
        ports:
            - '${APP_PORT:-80}:80'
            - '${SSL_APP_PORT:-443}:443'
        volumes:
            - '.:/var/www/html'
        networks:
            - '${APP_NETWORK:-sail}'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-123456}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-crud}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        container_name: mysql
        volumes:
            - 'data:/var/lib/mysql'
            - ./docker/mysql:/etc/mysql/conf.d
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD:-123456}'
            retries: 3
            timeout: 5s
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST:-mysql}
        restart: always
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
networks:
    sail:
        driver: bridge
volumes:
    data:
        driver: local
